name: build dpapi-reader

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: build
        working-directory: DPAPI-reader
        run: go build -o DPAPI-reader.exe .

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: DPAPI-reader/DPAPI-reader.exe
